name: line_function_calculator
description: Line function calculator.
publish_to: 'none' 
version: 1.2.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  file_picker: ^6.0.0
  flutter:
    sdk: flutter
  function_tree: ^0.9.0
  provider: ^6.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true